import { CaptionTemplate } from '../types';

export const CAPTION_TEMPLATES: CaptionTemplate[] = [
  // VIRAL CREATORS
  {
    id: 'hormozi-gold',
    name: 'Hormozi Gold',
    category: 'viral',
    description: 'Ultra-bold uppercase with punchy yellow active word & thick outline',
    fontFamily: "'Montserrat', 'Arial Black', sans-serif",
    fontWeight: 900,
    fontSize: 44,
    textColor: '#FFFFFF',
    highlightColor: '#FFDF00',
    secondaryColor: '#22C55E',
    bgColor: 'rgba(0, 0, 0, 0)',
    bgPadding: 8,
    borderRadius: 8,
    textTransform: 'uppercase',
    outlineWidth: 6,
    outlineColor: '#000000',
    shadowBlur: 12,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    animation: 'bounce',
  },
  {
    id: 'beast-impact',
    name: 'MrBeast Impact',
    category: 'viral',
    description: 'High-energy black boxed pill with energetic yellow text',
    fontFamily: "'Fredoka', 'Montserrat', sans-serif",
    fontWeight: 800,
    fontSize: 42,
    textColor: '#FFFFFF',
    highlightColor: '#FFE600',
    secondaryColor: '#38BDF8',
    bgColor: '#000000',
    bgPadding: 12,
    borderRadius: 14,
    textTransform: 'uppercase',
    outlineWidth: 0,
    outlineColor: '#000000',
    shadowBlur: 16,
    shadowColor: 'rgba(0, 0, 0, 0.7)',
    animation: 'pop',
    boxPerPhrase: true,
  },
  {
    id: 'ali-clean',
    name: 'Ali Clean Sub',
    category: 'viral',
    description: 'Modern minimalist soft gray-white with calm pop highlight',
    fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 36,
    textColor: '#94A3B8',
    highlightColor: '#FFFFFF',
    secondaryColor: '#60A5FA',
    bgColor: 'rgba(15, 23, 42, 0.75)',
    bgPadding: 10,
    borderRadius: 20,
    textTransform: 'none',
    outlineWidth: 0,
    outlineColor: '#000000',
    shadowBlur: 10,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    animation: 'fade',
    boxPerPhrase: true,
  },
  {
    id: 'iman-luxury',
    name: 'Iman Luxury Serif',
    category: 'viral',
    description: 'Refined editorial serif with shimmering amber highlights',
    fontFamily: "'Playfair Display', Georgia, serif",
    fontWeight: 800,
    fontSize: 40,
    textColor: '#E2E8F0',
    highlightColor: '#F59E0B',
    secondaryColor: '#D97706',
    bgColor: 'rgba(0, 0, 0, 0.4)',
    bgPadding: 8,
    borderRadius: 6,
    textTransform: 'none',
    outlineWidth: 2,
    outlineColor: '#000000',
    shadowBlur: 12,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    animation: 'fade',
    italic: true,
  },
  {
    id: 'dan-koe-mono',
    name: 'Dan Koe Thinker',
    category: 'viral',
    description: 'Crisp monospace typewriter aesthetic with lime green accent',
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: 34,
    textColor: '#E2E8F0',
    highlightColor: '#84CC16',
    secondaryColor: '#A3E635',
    bgColor: '#090D14',
    bgPadding: 10,
    borderRadius: 8,
    textTransform: 'none',
    outlineWidth: 1,
    outlineColor: '#1E293B',
    shadowBlur: 8,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    animation: 'pop',
    boxPerPhrase: true,
  },

  // NEON & FUTURISTIC
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk 2077',
    category: 'neon',
    description: 'Electric cyan and magenta glow with high-voltage punch',
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 800,
    fontSize: 42,
    textColor: '#E0F2FE',
    highlightColor: '#06B6D4',
    secondaryColor: '#EC4899',
    bgColor: 'rgba(10, 10, 20, 0.8)',
    bgPadding: 10,
    borderRadius: 8,
    textTransform: 'uppercase',
    outlineWidth: 2,
    outlineColor: '#083344',
    shadowBlur: 20,
    shadowColor: '#06B6D4',
    animation: 'glow',
    glow: true,
  },
  {
    id: 'matrix-terminal',
    name: 'Matrix Code',
    category: 'neon',
    description: 'Neon green terminal glowing text with dark tech backing',
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: 36,
    textColor: '#86EFAC',
    highlightColor: '#22C55E',
    secondaryColor: '#15803D',
    bgColor: 'rgba(5, 20, 10, 0.85)',
    bgPadding: 8,
    borderRadius: 6,
    textTransform: 'uppercase',
    outlineWidth: 0,
    outlineColor: '#000',
    shadowBlur: 18,
    shadowColor: '#22C55E',
    animation: 'glow',
    glow: true,
  },
  {
    id: 'synthwave-sunset',
    name: 'Synthwave 80s',
    category: 'neon',
    description: 'Warm coral gradient glow with purple accents',
    fontFamily: "'Outfit', 'Montserrat', sans-serif",
    fontWeight: 800,
    fontSize: 44,
    textColor: '#FDE047',
    highlightColor: '#F43F5E',
    secondaryColor: '#A855F7',
    bgColor: 'rgba(25, 10, 35, 0.8)',
    bgPadding: 10,
    borderRadius: 12,
    textTransform: 'uppercase',
    outlineWidth: 3,
    outlineColor: '#4C0519',
    shadowBlur: 18,
    shadowColor: '#F43F5E',
    animation: 'glow',
    glow: true,
  },
  {
    id: 'electric-violet',
    name: 'Electric Violet',
    category: 'neon',
    description: 'Deep violet glow with radiant lavender active words',
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 800,
    fontSize: 40,
    textColor: '#FFFFFF',
    highlightColor: '#A855F7',
    secondaryColor: '#C084FC',
    bgColor: 'rgba(30, 15, 50, 0.75)',
    bgPadding: 10,
    borderRadius: 10,
    textTransform: 'none',
    outlineWidth: 2,
    outlineColor: '#581C87',
    shadowBlur: 16,
    shadowColor: '#A855F7',
    animation: 'glow',
    glow: true,
  },

  // MODERN & SOCIAL
  {
    id: 'karaoke-bounce',
    name: 'Karaoke Pop',
    category: 'modern',
    description: 'Smooth word-by-word scale bounce in vibrant sunny yellow',
    fontFamily: "'Outfit', 'Space Grotesk', sans-serif",
    fontWeight: 800,
    fontSize: 44,
    textColor: '#FFFFFF',
    highlightColor: '#FACC15',
    secondaryColor: '#38BDF8',
    bgColor: 'rgba(0, 0, 0, 0)',
    bgPadding: 0,
    borderRadius: 0,
    textTransform: 'none',
    outlineWidth: 5,
    outlineColor: '#000000',
    shadowBlur: 10,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    animation: 'bounce',
  },
  {
    id: 'pill-badge',
    name: 'Floating Pill Badge',
    category: 'modern',
    description: 'Individual rounded colored pill highlight per active word',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontWeight: 800,
    fontSize: 38,
    textColor: '#FFFFFF',
    highlightColor: '#10B981',
    secondaryColor: '#064E3B',
    bgColor: 'rgba(15, 23, 42, 0.8)',
    bgPadding: 10,
    borderRadius: 999,
    textTransform: 'none',
    outlineWidth: 0,
    outlineColor: '#000',
    shadowBlur: 12,
    shadowColor: 'rgba(0, 0, 0, 0.6)',
    animation: 'pop',
    boxPerWord: true,
  },
  {
    id: 'bionic-speed',
    name: 'Bionic Speed Read',
    category: 'modern',
    description: 'First 2-3 letters of each word highlighted for ultra-fast reading',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 38,
    textColor: '#CBD5E1',
    highlightColor: '#38BDF8',
    secondaryColor: '#0284C7',
    bgColor: 'rgba(0, 0, 0, 0.7)',
    bgPadding: 10,
    borderRadius: 10,
    textTransform: 'none',
    outlineWidth: 2,
    outlineColor: '#000',
    shadowBlur: 8,
    shadowColor: 'rgba(0, 0, 0, 0.7)',
    animation: 'none',
    bionic: true,
    boxPerPhrase: true,
  },
  {
    id: 'comic-punch',
    name: 'Comic Pop Art',
    category: 'creative',
    description: 'Tilted playful comic letters with thick bold black cartoon stroke',
    fontFamily: "'Bungee', 'Fredoka', cursive",
    fontWeight: 900,
    fontSize: 42,
    textColor: '#FFFFFF',
    highlightColor: '#FB923C',
    secondaryColor: '#FACC15',
    bgColor: 'rgba(0, 0, 0, 0)',
    bgPadding: 0,
    borderRadius: 0,
    textTransform: 'uppercase',
    outlineWidth: 7,
    outlineColor: '#000000',
    shadowBlur: 0,
    shadowColor: '#000000',
    animation: 'bounce',
  },
  {
    id: 'y2k-glossy',
    name: 'Y2K Retro Candy',
    category: 'creative',
    description: 'Pastel purple & mint bubblegum aesthetic with bubbly curve',
    fontFamily: "'Fredoka', cursive",
    fontWeight: 700,
    fontSize: 42,
    textColor: '#FDF4FF',
    highlightColor: '#C084FC',
    secondaryColor: '#34D399',
    bgColor: 'rgba(74, 29, 150, 0.65)',
    bgPadding: 12,
    borderRadius: 24,
    textTransform: 'none',
    outlineWidth: 3,
    outlineColor: '#2E1065',
    shadowBlur: 14,
    shadowColor: '#C084FC',
    animation: 'pop',
    boxPerPhrase: true,
  },
  {
    id: 'duet-interview',
    name: 'Duet Dialogue',
    category: 'creative',
    description: 'Dynamic two-color coding for podcasts & interviews',
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 38,
    textColor: '#F8FAFC',
    highlightColor: '#38BDF8',
    secondaryColor: '#FBBF24',
    bgColor: 'rgba(15, 23, 42, 0.85)',
    bgPadding: 10,
    borderRadius: 12,
    textTransform: 'none',
    outlineWidth: 0,
    outlineColor: '#000',
    shadowBlur: 10,
    shadowColor: 'rgba(0,0,0,0.5)',
    animation: 'pop',
    boxPerPhrase: true,
  },

  // MINIMAL & RETRO
  {
    id: 'cinema-letterbox',
    name: 'Cinema Subtitle',
    category: 'minimal',
    description: 'Classic film documentary subtitle band with clean yellow text',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontSize: 32,
    textColor: '#FEF08A',
    highlightColor: '#FFFFFF',
    secondaryColor: '#FACC15',
    bgColor: 'rgba(0, 0, 0, 0.85)',
    bgPadding: 6,
    borderRadius: 4,
    textTransform: 'none',
    outlineWidth: 0,
    outlineColor: '#000',
    shadowBlur: 4,
    shadowColor: 'rgba(0,0,0,0.8)',
    animation: 'none',
    boxPerPhrase: true,
  },
  {
    id: 'matte-stealth',
    name: 'Stealth Matte',
    category: 'minimal',
    description: 'Sleek dark matte pill with ice white and crimson punch',
    fontFamily: "'Outfit', sans-serif",
    fontWeight: 700,
    fontSize: 36,
    textColor: '#94A3B8',
    highlightColor: '#F43F5E',
    secondaryColor: '#FFFFFF',
    bgColor: '#111419',
    bgPadding: 10,
    borderRadius: 12,
    textTransform: 'none',
    outlineWidth: 1,
    outlineColor: '#262B33',
    shadowBlur: 10,
    shadowColor: 'rgba(0,0,0,0.7)',
    animation: 'pop',
    boxPerPhrase: true,
  },
  {
    id: 'hollow-outline',
    name: 'Hollow Stroke',
    category: 'minimal',
    description: 'Clean outlined inactive words with solid glowing active word',
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 800,
    fontSize: 42,
    textColor: 'transparent',
    highlightColor: '#38BDF8',
    secondaryColor: '#FFFFFF',
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    borderRadius: 0,
    textTransform: 'uppercase',
    outlineWidth: 2,
    outlineColor: '#FFFFFF',
    shadowBlur: 10,
    shadowColor: '#38BDF8',
    animation: 'glow',
  },
  {
    id: 'vhs-glitch-retro',
    name: 'Retro 90s VHS',
    category: 'retro',
    description: 'Analog video cassette tape font with chromatic offset & date mark',
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 800,
    fontSize: 36,
    textColor: '#FDE047',
    highlightColor: '#EC4899',
    secondaryColor: '#06B6D4',
    bgColor: 'rgba(0, 0, 0, 0.65)',
    bgPadding: 8,
    borderRadius: 0,
    textTransform: 'uppercase',
    outlineWidth: 2,
    outlineColor: '#000000',
    shadowBlur: 6,
    shadowColor: '#EC4899',
    animation: 'glitch',
    boxPerPhrase: true,
  },
  {
    id: 'fire-hype',
    name: 'Fire & Hype',
    category: 'creative',
    description: 'Bright fiery flame colors with explosive bounce highlight',
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    fontSize: 44,
    textColor: '#FFFFFF',
    highlightColor: '#FF4500',
    secondaryColor: '#FFD700',
    bgColor: 'rgba(0, 0, 0, 0.3)',
    bgPadding: 6,
    borderRadius: 8,
    textTransform: 'uppercase',
    outlineWidth: 5,
    outlineColor: '#1A0000',
    shadowBlur: 14,
    shadowColor: '#FF4500',
    animation: 'bounce',
  },
  {
    id: 'glow-underline',
    name: 'Underline Accent',
    category: 'modern',
    description: 'Clean typographic layout with glowing neon underline indicator',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontWeight: 700,
    fontSize: 38,
    textColor: '#FFFFFF',
    highlightColor: '#A855F7',
    secondaryColor: '#38BDF8',
    bgColor: 'rgba(15, 23, 42, 0.7)',
    bgPadding: 10,
    borderRadius: 14,
    textTransform: 'none',
    outlineWidth: 0,
    outlineColor: '#000',
    shadowBlur: 10,
    shadowColor: 'rgba(0,0,0,0.6)',
    animation: 'pop',
    boxPerPhrase: true,
  },
  {
    id: 'editorial-vogue',
    name: 'Editorial Minimalist',
    category: 'minimal',
    description: 'Clean black & ivory magazine style with subtle gold accents',
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: 36,
    textColor: '#F8FAFC',
    highlightColor: '#FCD34D',
    secondaryColor: '#E2E8F0',
    bgColor: '#000000',
    bgPadding: 10,
    borderRadius: 0,
    textTransform: 'none',
    outlineWidth: 0,
    outlineColor: '#000',
    shadowBlur: 0,
    shadowColor: '#000',
    animation: 'fade',
    boxPerPhrase: true,
  },
];

export const COLOR_SWATCHES = [
  '#FFDF00', // Hormozi Yellow
  '#FFE600', // MrBeast Yellow
  '#22C55E', // Viral Green
  '#06B6D4', // Cyan
  '#38BDF8', // Sky Blue
  '#EC4899', // Hot Pink
  '#A855F7', // Violet
  '#F97316', // Orange
  '#EF4444', // Red
  '#FFFFFF', // Pure White
  '#94A3B8', // Slate Gray
  '#000000', // Deep Black
];

export const FONT_OPTIONS = [
  { label: 'Space Grotesk (Modern Tech)', value: "'Space Grotesk', sans-serif" },
  { label: 'Montserrat (Ultra Bold Viral)', value: "'Montserrat', sans-serif" },
  { label: 'Outfit (Sleek Clean)', value: "'Outfit', sans-serif" },
  { label: 'Plus Jakarta Sans (Crisp UI)', value: "'Plus Jakarta Sans', sans-serif" },
  { label: 'Inter (Classic Minimalist)', value: "'Inter', sans-serif" },
  { label: 'Fredoka (Punchy Rounded)', value: "'Fredoka', cursive" },
  { label: 'Bungee (Comic Bold)', value: "'Bungee', cursive" },
  { label: 'JetBrains Mono (Developer)', value: "'JetBrains Mono', monospace" },
  { label: 'Playfair Display (Luxury Serif)', value: "'Playfair Display', serif" },
];
